language: python

services: # => 3
      - postgresql

env: # => 4
    -DJANGO=2.2.1 DB=postregsql
    
install: # => 5
      - pip install -r requirements.txt
    
# before_script: # => 6
#       - psql -e 'create database test;' -u root


script: # => 7
      #- cd django_api
      - source ~/.env/bin/activate
      - python manage.py syncdb --noinput
      - python manage.py test
services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=django_restapi.settings
  - export PYTHONPATH=$HOME/builds/AlbertBuluma/django_restapi
  - export PIP_USE_MIRRORS=true

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

deploy:
  provider: heroku
  api_key:
    secure: "385b3e25-f8d4-4f8a-b232-f73776b4884d"