language: python

services: # => 3
      - postgresql

env: # => 4
    -DJANGO=2.2.1 DB=postregsql
    
install: # => 5
      - pip install -r requirements.txt
    
# before_script: # => 6
#       - mysql -e 'create database test;' -u root
script: # => 7
      #- cd django_api
      - manage.py test

deploy:
  provider: heroku
  api_key:
    secure: "385b3e25-f8d4-4f8a-b232-f73776b4884d"